resources:
- busybox-sfs-1.yaml
- busybox-sfs-2.yaml
- busybox-sfs-3.yaml
- busybox-sfs-4.yaml
- busybox-sfs-5.yaml
images:
- name: quay.io/ocsci/rdr-ocs-workload
  newTag: latest
  digest: sha256:14538cba9e2bf3d9aa0a575bc750f5d4647baca6e7bb80541a761ba279dbc6e1
