resources:
  - busybox-sfs-1.yaml
  - busybox-sfs-2.yaml
  - busybox-sfs-3.yaml
  - busybox-sfs-4.yaml
  - busybox-sfs-5.yaml
images:
  - name: quay.io/ocsci/rdr-ocs-workload
    newTag: latest
    digest: sha256:1655e9041501955c169d2bd7c6b5c4153b4d47efe70efebf7d1f141efc890714
