---
apiVersion: v1
kind: Secret
metadata:
  name: vm-secret-1
type: Opaque
stringData:
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8jblXxGKKHvJtVy1vVxJqwqd+RKXS5Ck5QsXYZ1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ user@example.com

# Made with Bob
