resources:
  - ../../../../cnv-workload/vm-resources/vm-workload-1
patches:
  - target:
      kind: PersistentVolumeClaim
      name: vm-1-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: localblock
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
