---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-fusion-pvc
  labels:
    appname: busybox-fusion
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: san-fs1
  resources:
    requests:
      storage: 5Gi

# Made with Bob
