resources:
- ../../../../busybox/base
patches:
  - target:
      kind: Deployment
      labelSelector: workloadpattern=simple_io
    patch: |-
      - op: replace
        path: /metadata/labels/appname
        value: busybox_app_1
  - target:
      kind: PersistentVolumeClaim
      labelSelector: appname=busybox_app1
    patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
      - op: replace
        path: /spec/storageClassName
        value: localblock
      - op: replace
        path: /metadata/labels/appname
        value: busybox_app1_agnostic_dr