---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-1
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-2
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-3
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-4
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-5
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-6
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-7
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-8
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-9
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-10
spec:
  template:
    spec:
      serviceAccountName: busybox-scc-sa
      containers:
      - name: busybox
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
