---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-2-rootdisk-pvc
  labels:
    appname: fedora-vm2
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: fedora-source
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: san-lg1-vm

# Made with Bob
