---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-2-datadisk-pvc
  labels:
    appname: fedora-vm2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: san-lg1

# Made with Bob
