resources:
- ../../../../base/statefulsets

patches:
- target:
    kind: StatefulSet
    name: busybox-sfs-.*
  patch: |-
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: ocs-storagecluster-cephfs
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/accessModes/0
      value: ReadWriteMany
