apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/statefulsets/busybox-sfs-1.yaml
- ../../../base/statefulsets/busybox-sfs-2.yaml
- ../../../base/statefulsets/busybox-sfs-3.yaml
- ../../../base/statefulsets/busybox-sfs-4.yaml
- ../../../base/statefulsets/busybox-sfs-5.yaml

patches:
- target:
    kind: StatefulSet
    name: busybox-sfs-.*
  patch: |-
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: ocs-storagecluster-ceph-rbd
