---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    appname: vm
  name: root-disk-vm-dv
spec:
  source:
    registry:
      url: docker://quay.io/ocsci/cirros-dd@sha256:90af9a70201a1c45ebb2c0ae92afbf0ec05b8b940f99afb163e8cc8cdbb057ee
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization