---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: rdr/busybox/cephfs/workloads/statefulsets
  labels:
    app: busybox-statefulset-sample
  name: busybox-statefulset-sub
spec:
    channel: ramen-busybox-statefulset-1-cephfs/ramen-gitops
    placement:
      placementRef:
        kind: Placement
        name: busybox-statefulset-placement
